# Basic Demo of Autodiff

#### (Note this demo is here for ease of access to users and similar demos can be found in milestone2.ipynb)


See below for a basic example of how the user can interact with our package:

The basic steps are:
0. Import package
1. Create a variable instantiated at an initial value 
    - Below we create variable x with a value of 0
2. Define a function 
    - Functions take variables as inputs and return new variables with updated value and gradient
    - Below we define the function $f(x) := sin(exp(x))$
3. Call the function and get the value and gradient of the resulting variable 


In [1]:
#%cd cs207-FinalProject
%pwd

'/Users/theoguenais/Desktop/Harvard/Harvard-Classes/CS207/cs207-FinalProject'

In [4]:
import numpy as np 
from autodiff.variable import Variable
import autodiff.function as F

# Define a variable with an initial value
x = Variable(0.)
print("Input x", x)

# Define a function
def my_func(x):
    return F.sin(F.exp(x))

# Variable z is the result of calling function on x
z = my_func(x)

# Get value and gradient of z
print("Output z", z)

# Alternatively, with direct access to the value and gradient attributes.
print('The value is: {}'.format(z.val))
print('The gradient is: {}'.format(z.grad))

Input x Value: [0.]
Gradient: [[1.]]
Output z Value: [0.84147098]
Gradient: 0.5403023058681398
The value is: [0.84147098]
The gradient is: 0.5403023058681398


# Simple Implementation of Newton's Method
As seen above, autodiff provides us with a natural way to define a specified function, by composition of elementary functions.  

Furthermore, autodiff objects can be used to implement higher level algorithms. For example, users of our package may be interested in appyling it to solve optimization problems. As such, we provide an example of how our package could be used to implement the Newton-Raphson method for root finding:

In [7]:
import numpy as np 
from autodiff.variable import Variable
import autodiff.function as F


def newtons_method(function, guess, epsilon):
    x = Variable(guess)
    f = function(x)
    i = 0
    max_out = False
    while abs(f.val) >= epsilon and max_out == False:
        x = x - f.val / f.grad
        f = function(x)
        print('Current x: {}'.format(x.val))
        i += 1
        if i >= 10000:
            max_out = True
    print('The root of the function is: {}'.format(x.val))
            

def my_func(x):
    return 5*(x-2)**3

guess = 5
epsilon = 0.000001

newtons_method(my_func, guess, epsilon)

Initializing the gradient with [[1.]]
Initializing the gradient with [[1.]]
Initializing the gradient with [[27.]]
Initializing the gradient with [[135.]]
Initializing the gradient with [[1.]]
Initializing the gradient with [[1.]]
Initializing the gradient with [[12.]]
Initializing the gradient with [[60.]]
Current x: [4.]
Initializing the gradient with [[1.]]
Initializing the gradient with [[1.]]
Initializing the gradient with [[5.33333333]]
Initializing the gradient with [[26.66666667]]
Current x: [3.33333333]
Initializing the gradient with [[1.]]
Initializing the gradient with [[1.]]
Initializing the gradient with [[2.37037037]]
Initializing the gradient with [[11.85185185]]
Current x: [2.88888889]
Initializing the gradient with [[1.]]
Initializing the gradient with [[1.]]
Initializing the gradient with [[1.05349794]]
Initializing the gradient with [[5.26748971]]
Current x: [2.59259259]
Initializing the gradient with [[1.]]
Initializing the gradient with [[1.]]
Initializing the grad

In [19]:
#Multivariable demo. Please play around to see the edge cases. If we want a function R^3->R.
X = Variable(np.array([1.5 ,5 ,10]))
x,y,z = F.unroll(X)

print('What does the full variable look like', X, '\n')
print('What do the unrolled variables look like', x,y,z, '\n')
#Operations
out = F.exp(x) + F.cos(y)
out += x
#=============
#Check whether it matches what we hoped ?
#===========
print('Our final variable', out, '\n')
print('Expected value', np.exp(X.val[0]) + np.cos(X.val[1]) + X.val[0])
print('Expected gradients', np.exp(X.val[0]) + 1, -np.sin(X.val[1]), 0)

What does the full variable look like Value: [ 1.5  5.  10. ]
Gradient: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

What do the unrolled variables look like Value: [1.5]
Gradient: [[1. 0. 0.]] Value: [5.]
Gradient: [[0. 1. 0.]] Value: [10.]
Gradient: [[0. 0. 1.]] 

Our variable Value: [6.26535126]
Gradient: [[5.48168907 0.95892427 0.        ]] 

Expected value 6.265351255801291
Expected gradients 5.4816890703380645 0.9589242746631385 0


In [21]:
#Mult.
mul = x*y*z 
print(mul)
print('Check', y.val*z.val, x.val*z.val, x.val*y.val)

Value: [75.]
Gradient: [[50.  15.   7.5]]


In [3]:
from autodiff.variable import Variable

In [4]:
import autodiff.function as F

/Users/theoguenais/Desktop/Harvard/Harvard-Classes/CS207/cs207-FinalProject/autodiff/function.py:379: UserWarning: Using the element-wise composition. Beta version. Not entirely tested.
  "Using the element-wise composition. Beta version. Not entirely tested.")
/Users/theoguenais/Desktop/Harvard/Harvard-Classes/CS207/cs207-FinalProject/autodiff/function.py:392: UserWarning: Using the element-wise composition. Beta version. Not entirely tested.
  "Using the element-wise composition. Beta version. Not entirely tested.")
/Users/theoguenais/Desktop/Harvard/Harvard-Classes/CS207/cs207-FinalProject/autodiff/function.py:405: UserWarning: Using the element-wise composition. Beta version. Not entirely tested.
  "Using the element-wise composition. Beta version. Not entirely tested.")
/Users/theoguenais/Desktop/Harvard/Harvard-Classes/CS207/cs207-FinalProject/autodiff/function.py:418: UserWarning: Using the element-wise composition. Beta version. Not entirely tested.
  "Using the element-wise co

In [11]:
#For some functions, namely exp, sin, cos, tan, we can directly use 
#some elementary-wise operators, the followig way:
X = Variable([1,2,4])
ew_W = F.ew_exp(X)
print(ew_W)
#===============
# By unroll and concatenating
#===============
x, y, z = X.unroll()
out_x, out_y, out_z = F.exp(x), F.exp(y), F.exp(z)
out_X = F.concat([out_x, out_y, out_z])
print('\n', out_X)

Value:
[[ 2.71828183]
 [ 7.3890561 ]
 [54.59815003]]
Gradient:
[[ 2.71828183  0.          0.        ]
 [ 0.          7.3890561   0.        ]
 [ 0.          0.         54.59815003]]

 Value:
[[ 2.71828183]
 [ 7.3890561 ]
 [54.59815003]]
Gradient:
[[ 2.71828183  0.          0.        ]
 [ 0.          7.3890561   0.        ]
 [ 0.          0.         54.59815003]]
